baseURL = "http://jpa.guramod.club/"
title = "HITszæ—¥è¯­ç¤¾"
theme = "PaperMod"
defaultContentLanguage = "zh-cn"
[languages] 
	[languages.zh-cn]
		languageName = "ä¸­æ–‡"
		weight = 1
	[languages.ja] 
		languageName = "æ—¥æœ¬èª"
		weight = 2

[params] 
	defaultTheme = "light"
	disableThemeToggle = false
	ShowReadingTime = false 
	description = "æ—¥æœ¬æ–‡åŒ– Ã— è¨€è¯­"
	customCSS = ["/css/custom.css"]
	ShowPostNavLinks = true
	ShowCodeCopyButtons = true
	ShowFooter = true
	[params.footer]
  		text = "æµ™ICPå¤‡2025206493å·"




[params.homeInfoParams]
	Title = "ğŸŒ¸ ã‚ˆã†ã“ãï¼HITSZæ—¥è¯­ç¤¾ã¸"
	Content = "ã“ã“ã§ã¯ç§ãŸã¡ã®æ´»å‹•ãƒ»ã‚¤ãƒ™ãƒ³ãƒˆãƒ»æ–‡åŒ–ã‚’ç´¹ä»‹ã—ã¾ã™ã€‚"

[menu] 
	[[menu.main]]
		name = "å…³äºæˆ‘ä»¬"
		url = "about"
	[[menu.main]]
		name = "æ´»åŠ¨"
		url = "events"
	[[menu.main]]
		name = "å…¬å‘Š"
		url = "news"
	[[menu.main]]
		name = "åŠ å…¥æˆ‘ä»¬"
		url = "join"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true